#!/bin/bash

. ./icons

batterytest=$(acpi -b)
if [[ $batterytest  != *Battery* ]] ; then
    exit 0;
fi

CHRGING=$(acpi -b | cut -d: -f2 | cut -d, -f1 | sed 's/ //g')
BAT=$(acpi -b | cut -d, -f2 | sed 's/ //g' | sed 's/%//g')
FULL=""

if [ $CHRGING = "Charging" ] ; then

  FULL="$SPAN$SPANEND $BAT%"

else

  if [ $BAT -le 15 ] ; then
    FULL="$SPANRED$SPANEND $BAT%%{F-}"
  else
    FULL="$SPAN$SPANEND $BAT%"
  fi

fi

echo "$FULL"
