#!/bin/sh
. ./icons

ISMUTE=$(pamixer --get-mute)
VOL=$(pamixer --get-volume)
if [ $ISMUTE = true ]; then
    FULL="$ICON_VOL_MUTE $VOL%"
else
    if [ "$VOL" -lt 40 ] ; then
        FULL="$ICON_VOL_LOW $VOL%"
    else
        FULL="$ICON_VOL_HIGH $VOL%"
    fi
fi

echo "$FULL"
