#!/bin/sh
. ./icons

ps -aux | grep openvpn | grep -v 'grep' | grep -v 'sed' > /dev/null
if [ $? -eq 1 ]; then
    FULL="$SPANRED$SPANEND No Connection"
else
    VPN=$(nmcli c show --active | grep vpn | awk '{ printf "%s\n", $1 }')
    FULL="$SPAN$SPANEND $VPN"
fi

echo "$FULL"
