#!/bin/bash

. ./icons

INTERFACE=$1
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

SSID=$(iwgetid -r)
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

printf '%s%s %s (%s%%)\n' "$SPAN" "$SPANEND" "$SSID" "$QUALITY"
