#!/bin/bash

start ()
{
    if pgrep "lemonbar" > /dev/null
    then
        printf "%s\n" "The panel is already running."
    else
        bash -c "cd ~/.config/panel/ && (nohup ./panel > /dev/null 2>&1) &"

        # move lower when fullscreen
        wid=$(xdo id -a "$PANEL_TOP_WM_NAME")
        tries_left=20
        while [ -z "$wid" ] && [ "$tries_left" -gt 0 ] ; do
            sleep 0.05
            wid=$(xdo id -a "$PANEL_TOP_WM_NAME")
            tries_left=$((tries_left - 1))
        done
        for w in $wid; do
            [ -n "$w" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$w"
        done

    fi
}

stop ()
{
    pkill -f "/bin/bash ./panel"
    pkill -f "/bin/bash modules/"
    pkill -f "/bin/sh modules/"
    pkill -f "python3 modules/"
}

toggle ()
{
    if pgrep "lemonbar" > /dev/null
    then
        printf "%s\n" "The panel is already running."
        stop
    else
        echo "Starting panel"
        start
    fi
}

if [ -n "$1" ] ; then
    if [ "$1" = "start" ] ; then
        start
    elif [ "$1" = "stop" ] ; then
        stop
    elif [ "$1" = "restart" ] ; then
        stop;
        start;
    fi
else
    toggle
fi
