#!/bin/bash

screenname="panelscreen"

is_panel_running ()
{
    if pgrep -f "polybar top" > /dev/null; then
        return 0
    else
        return 1
    fi
}

start ()
{
    if ! is_panel_running ; then
        printf "%s\n" "Starting panel"
        bash -c "screen -dmS $screenname polybar top -r"
    fi
}

stop ()
{
    printf "%s\n" "Stopping panel"
    screen -X -S $screenname kill
    pkill polybar
    pkill -f '.config/polybar/modules/'
    pkill redshift
}

toggle ()
{
    if ! is_panel_running ; then
        start
    else
        stop
    fi
}

if [ -n "$1" ] ; then
    if [ "$1" = "start" ] ; then
        start
    elif [ "$1" = "stop" ] ; then
        stop
    elif [ "$1" = "restart" ] ; then
        stop;
        start;
    fi
else
    toggle
fi
