#! /bin/sh

#sxhkd &
feh --bg-fill ~/Sync/wallpapers/Universe/Beautiful_Dream-3000x1688.png
compton --config ~/.config/compton.conf &
redshift &
xautolock -time 10 -locker '/home/lukas/.config/bspwm/scripts/lock_test_fullscreen.sh' &

~/.config/bspwm/scripts/disable-fullscreen-standby.sh &
xset dpms 0 640 660
xset s 0 0
xset s off

setxkbmap -option grp:switch,grp:shift_toggle,grp_led:scroll us,de -variant ,qwerty

bspc config border_width            4
bspc config window_gap              30

# bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config focus_follows_pointer   true

bspc config active_border_color   "#5F6980"
bspc config focused_border_color  "#5294E2"
bspc config presel_feedback_color "#748FA4"
bspc config normal_border_color   "#5F6980"

bspc monitor -d 1 2 3 4 5 6

# bspc rule -a Gimp desktop=^8 state=floating follow=on
# web browsers
bspc rule -a chromium                   desktop=^1 follow=off
bspc rule -a google-chrome              desktop=^1 follow=off

# ide
bspc rule -a jetbrains-idea-ce          desktop=^2 follow=off
bspc rule -a jetbrains-webstorm         desktop=^2 follow=off
bspc rule -a jetbrains-idea             desktop=^2 follow=off

# messaging
bspc rule -a Thunderbird                desktop=^3 follow=off

# music players
bspc rule -a "Google Play Music"        desktop=^4 follow=off

#voice
bspc rule -a "TeamSpeak 3"              desktop=^6 follow=off

bspc config external_rules_command "$(realpath ~/.config/bspwm/external_rules)"

toggle_panel start

#xsetroot -cursor_name left_ptr
