#! /bin/sh

sxhkd &

feh --bg-fill ~/Sync/wallpapers/Games/The\ Last\ Of\ Us/II_Trailer_04.png
compton --config ~/.config/compton.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

~/.config/bspwm/scripts/disable_fullscreen_standby.sh &
~/.local/bin/redshift_wrapper &
xset dpms 0 640 660
xset s 0 0
xset s off

setxkbmap -option grp:switch,grp:shift_toggle,grp_led:scroll us,de -variant ,qwerty

bspc config border_width                4

bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config paddingless_monocle         true
bspc config focus_follows_pointer       true
bspc config merge_overlapping_monitors  true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc config active_border_color         "#5F6980"
bspc config focused_border_color        "#CCCCCC"
bspc config presel_feedback_color       "#748FA4"
bspc config normal_border_color         "#2f343f"

bspc monitor -d 1 2 3 4 5 6

# web browsers
bspc rule -a chromium                               desktop=^1 follow=off
bspc rule -a google-chrome                          desktop=^1 follow=off

# ide
bspc rule -a jetbrains-idea-ce                      desktop=^2 follow=off
bspc rule -a jetbrains-webstorm                     desktop=^2 follow=off
bspc rule -a jetbrains-idea                         desktop=^2 follow=off

# messaging
bspc rule -a Thunderbird                            desktop=^3 follow=off

# music players
bspc rule -a "Google Play Music Desktop Player"     desktop=^4 follow=off
bspc rule -a Upplay                                 desktop=^4 follow=off

#voice
bspc rule -a "TeamSpeak 3"                          desktop=^6 follow=off

bspc config external_rules_command "$(realpath ~/.config/bspwm/external_rules)"

if [ "shepard" = "$(uname -n)" ] ; then

    bspc config top_padding                 30
    bspc config window_gap                  50
    xautolock -time 10 -locker 'lock_test_fullscreen.sh' -killtime 60 -killer 'suspend_test_fullscreen.sh' &

else

    bspc config top_padding                 30
    bspc config window_gap                  20
    xautolock -time 5 -locker 'lock_test_fullscreen.sh' -killtime 15 -killer 'suspend_test_fullscreen.sh' &

fi

toggle_panel start
xsetroot -cursor_name left_ptr
