#! /bin/bash

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")

# echo -ne "id $wid\nclass $class\ninst $instance\ntitle $title\n" >> /tmp/extout.txt

if [ "$class" = "chromium" ] ; then
    if [ "$instance" = "crx_bikioccmkafdpakkkcpdbppfkghcmihk" ] ; then
        echo "desktop=^3 follow=off"
    else
        echo "desktop=^1 follow=off"
    fi
elif [ "$class" = "Steam" ] ; then
    case "$title" in
        "Friends")
            echo "state=floating follow=off"
        "Steam - Update News"*)
            echo "-c"
        *)
            echo "desktop=^5 follow=off"
    esac
fi
