#! /bin/bash

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")

# echo -ne "id $wid\nclass $class\ninst $instance\ntitle $title\n" >> /tmp/extout.txt

if [ "$class" = "chromium" ] ; then
    if [ "$instance" = "crx_bikioccmkafdpakkkcpdbppfkghcmihk" ] ; then
        echo "desktop=^3"
    else
        echo "desktop=^1"
    fi
elif [ "$class" = "Steam" ] || [ "$title" = "Steam" ] ; then
    case "$title" in
        "Steam - Update News"*)
            echo "-c"
            ;;
	"Friends")
            echo "split_ratio=0.2 split_dir=west"
            ;&
        "Steam")
            echo "split_ratio=0.8 split_dir=west"
            ;&
        *)
            echo "desktop=^5 floating=on"
            ;;
    esac
fi
