#!/bin/bash

display=$1

clock() {
    DATE=$(~/.config/lemonbar/modules/date.sh)
    echo -n "$DATE"
}

battery() {
    ~/.config/lemonbar/modules/battery.sh &
}

volume() {
	~/.config/lemonbar/modules/volume.sh &
}

brightness() {
	~/.config/lemonbar/modules/brightness.sh &
}

music() {
	~/.config/lemonbar/modules/mediaplayer.py &
}

ws(){
	(~/.config/lemonbar/modules/ws.py $display) &
}

ssid() {
	~/.config/lemonbar/modules/ssid.sh &
}

vpn() {
	~/.config/lemonbar/modules/vpn.sh &
}

colortemp() {
	~/.config/lemonbar/modules/colortemp.sh &
}

ws
music
volume
colortemp
vpn

if [ "$display" != "LVDS1" ]; then
	while true; do
		WS=$(cat ~/.config/lemonbar/modules/ws.out)
		MP=$(cat ~/.config/lemonbar/modules/mediaplayer.out)
		VOL=$(cat ~/.config/lemonbar/modules/volume.out)
		COL=$(cat ~/.config/lemonbar/modules/colortemp.out)
		VPN=$(cat ~/.config/lemonbar/modules/vpn.out)

		echo "%{l} $WS $MP %{c}$(clock) %{r}$VOL | $COL | $VPN "

		sleep 0.1;
	done
else
	battery
	brightness
	ssid
	while true; do
		WS=$(cat ~/.config/lemonbar/modules/ws.out)
		MP=$(cat ~/.config/lemonbar/modules/mediaplayer.out)
		VOL=$(cat ~/.config/lemonbar/modules/volume.out)
		COL=$(cat ~/.config/lemonbar/modules/colortemp.out)
		VPN=$(cat ~/.config/lemonbar/modules/vpn.out)
		BAT=$(cat ~/.config/lemonbar/modules/battery.out)
		BRI=$(cat ~/.config/lemonbar/modules/brightness.out)
		WIFI=$(cat ~/.config/lemonbar/modules/ssid.out)
		
		echo "%{l} $WS $MP %{c}$(clock) %{r}%BRI | %BAT | $SSID | $VOL | $COL | $VPN "

		sleep 0.1;

#		echo -n "%{l} $(ws) | $(music) %{c}$(clock) %{r} $(brightness) | $(battery) | $(ssid) | $(volume) | $(colortemp) | $(vpn) "
#		sleep 1;
	done
fi
