#!/bin/bash

display=$1

clock() {
    DATE=$(~/.config/lemonbar/modules/date.sh)
    echo -n "$DATE"
}

battery() {
    BAT=$(~/.config/lemonbar/modules/battery.sh)
    echo -n "$BAT"
}

volume() {
	VOL=$(~/.config/lemonbar/modules/volume.sh)
	echo -n "$VOL"
}

brightness() {
	BRIGHT=$(~/.config/lemonbar/modules/brightness.sh)
	echo -n "$BRIGHT"
}

music() {
	nowplaying=$(~/.config/lemonbar/modules/lemonnuvola.py)
	echo -n "${nowplaying}"
}

ws(){
	dasd="~/.config/lemonbar/ws.py $display"
	eval $dasd
#	echo "$dasd"
}

ssid() {
	SSID=$(~/.config/lemonbar/modules/ssid.sh)
	echo -n "$SSID"
}

vpn() {
	VPN=$(~/.config/lemonbar/modules/vpn.sh)
	echo -n "$VPN"
}

colortemp() {
	TEMP=$(~/.config/lemonbar/modules/colortemp.sh)
	echo -n "$TEMP"
}

pidgin() {
	UNSEEN=$(~/.config/lemonbar/modules/pidgin.py)
	echo -n "$UNSEEN"
}

if [ "$display" != "LVDS1" ]; then
	while true; do
		echo "%{l} $(ws) | $(music) %{c}$(clock) %{r}$(volume) | $(colortemp) | $(vpn) "
		sleep 0.1;
	done
else
	while true; do
		echo "%{l} $(ws) | $(music) %{c}$(clock) %{r} $(brightness) | $(battery) | $(ssid) | $(volume) | $(colortemp) | $(vpn) "
		sleep 1;
	done
fi
