#!/bin/bash

display=$1

clock() {
    DATE=$(~/.config/lemonbar/modules/date.sh)
    echo -n "$DATE"
}

battery() {
    ~/.config/lemonbar/modules/battery.sh &
}

volume() {
    ~/.config/lemonbar/modules/volume.sh &
}

brightness() {
    ~/.config/lemonbar/modules/brightness.sh &
}

music() {
    ~/.config/lemonbar/modules/mediaplayer.py &
}

ws(){
    (~/.config/lemonbar/modules/ws.py $display) &
}

ssid() {
    ~/.config/lemonbar/modules/ssid.sh &
}

vpn() {
    ~/.config/lemonbar/modules/vpn.sh &
}

colortemp() {
    ~/.config/lemonbar/modules/colortemp.sh &
}

mkdir /tmp/lemon
ws
music
volume
colortemp
vpn

if [ "$display" != "LVDS1" ]; then
    while true; do
        WS=$(cat /tmp/lemon/ws.out)
        MP=$(cat /tmp/lemon/mediaplayer.out)
        VOL=$(cat /tmp/lemon/volume.out)
        COL=$(cat /tmp/lemon/colortemp.out)
        VPN=$(cat /tmp/lemon/vpn.out)

        echo "%{l} $WS $MP %{c}$(clock) %{r}$VOL | $COL | $VPN "

        sleep 0.1;
    done
else
    battery
    brightness
    ssid
    while true; do
        WS=$(cat /tmp/lemon/ws.out)
        MP=$(cat /tmp/lemon/mediaplayer.out)
        VOL=$(cat /tmp/lemon/volume.out)
        COL=$(cat /tmp/lemon/colortemp.out)
        VPN=$(cat /tmp/lemon/vpn.out)
        BAT=$(cat /tmp/lemon/battery.out)
        BRI=$(cat /tmp/lemon/brightness.out)
        WIFI=$(cat /tmp/lemon/ssid.out)
        
        echo "%{l} $WS $MP %{c}$(clock) %{r}$BRI | $BAT | $SSID | $VOL | $COL | $VPN "

        sleep 0.1;

#       echo -n "%{l} $(ws) | $(music) %{c}$(clock) %{r} $(brightness) | $(battery) | $(ssid) | $(volume) | $(colortemp) | $(vpn) "
#       sleep 1;
    done
fi
