#!/bin/bash
SPAN="<span font_desc='Material Icons 12' rise='-2000'>"
SPANRED="<span font_desc='Material Icons 12' foreground='#ff6961' rise='-2000'>"

SPANEND="</span>"

ICON_VOL_LOW="$SPAN$SPANEND"
ICON_VOL_HIGH="$SPAN$SPANEND"
ICON_VOL_MUTE="$SPANRED$SPANEND"

#workspaces
SPANOCC="<span font_desc='Material Icons 12' foreground='#ffffff'>"
SPANRED="<span font_desc='Material Icons 12' foreground='#ff6961'>"
SPANFREE="<span font_desc='Material Icons 12' foreground='#788491'>"
SPANEND="</span>"

ICON_WS_FREE="$SPANFREE$SPANEND"

ICON_WS_OCCUPIED="$SPANOCC$SPANEND"

ICON_WS_FOCUSED="$SPANOCC$SPANEND"

ICON_WS_URGENT="$SPANRED$SPANEND"

ICON_WS_URGENT_FOCUSED="$SPANRED$SPANEND"

export SPAN SPANRED SPANEND ICON_VOL_LOW ICON_VOL_HIGH ICON_VOL_MUTE ICON_WS_FREE ICON_WS_OCCUPIED ICON_WS_FOCUSED ICON_WS_URGENT_FOCUSED ICON_WS_URGENT
