#!/usr/bin/env python3

import sys
import i3ipc


class i3subscribe:

    def connect(self):
        # Create the Connection object that can be used to send commands
        # and subscribe to events.
        self.conn = i3ipc.Connection()

    def on_event(self, ipc, e):
        print("Event occured", flush=True)

    def subscribe(self, event):
        # Subscribe to the workspace event
        self.conn.on(event, self.on_event)

    def __init__(self):
        if len(sys.argv) > 1:
            self.connect()
            self.subscribe(sys.argv[1])
            # Start the main loop and wait for events to come in.
            self.conn.main()


if __name__ == '__main__':
    try:
        i3subscribe()
    except Exception as e:
        pass
