#!/bin/bash

. ./config

printBattery() {

    batterytest=$(acpi -b)
    if [[ $batterytest  != *Battery* ]] ; then
        return 0;
    fi

    CHRGING=$(acpi -a)
    BAT=$(acpi -b | cut -d, -f2 | sed 's/ //g' | sed 's/%//g')
    FULL=""

    if [[ $CHRGING = *"on-line"* ]] ; then

      FULL="$BATTERY_ICON_CHARGING $BAT%"

    else

      if [ $BAT -le 15 ] ; then
        FULL="$BATTERY_ICON_CRITICAL $BAT%"
      else
        FULL="$BATTERY_ICON $BAT%"
      fi

    fi

    printf "%s\n" "$FULL"

}

printBattery

while true; do
    inotifywait -q -e close /sys/class/power_supply/BAT0/charge_now > /dev/null 2>&1
    printBattery
done
