#!/bin/bash

. ./config

# This is shit...
SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )""/""$(basename $0)"

HOSTS=("localhost" "gimli")

STATUS_PLAYING=""
STATUS_PAUSED=""
STATUS_STOPPED=""
STATUS_ERROR=""

PLAY="%{A1:mpc $HOST_CMD play:}"
PAUSE="%{A1:mpc $HOST_CMD pause:}"
PREV="%{A2:mpc $HOST_CMD prev:}"
NEXT="%{A3:mpc $HOST_CMD next:}"

# Use first host if none given
if [ -z "$1" ] ; then
    HOST="${HOSTS[0]}"
else
    HOST="$1"
fi
HOST_CMD="-h $HOST"

switchHost() {
    if [[ "${HOSTS[-1]}" = "$HOST" ]]; then
        HOST="${HOSTS[0]}";
    else
        for i in "${!HOSTS[@]}"; do
            if [[ "${HOSTS[$i]}" = "${HOST}" ]]; then
                HOST=${HOSTS[$(($i + 1))]};
                # echo "${i}";
                break;
            fi
        done
    fi
    notify-send "Switching MPD" "Now connecting to $HOST"
    exec $SCRIPT $HOST
}

# execute switchHost when receiving SIGUSR1
trap switchHost USR1

printTrack() {
    song=$(mpc $HOST_CMD current)
    status=$(mpc $HOST_CMD status)

    case $status in
        *"[playing]"*)
            FULL="$PAUSE""$PREV""$NEXT""$STATUS_PLAYING ""$song""%{A}%{A}%{A}"
        ;;
        *"[paused]"*)
            FULL="$PLAY""$PREV""$NEXT""$STATUS_PAUSED ""$song""%{A}%{A}%{A}"
        ;;
        *)
            FULL="$STATUS_STOPPED ""Not playing"
        ;;
    esac

    printf "%s\n" "$FULL"
}

loop() {
    while true; do
        printTrack
        mpc $HOST_CMD idleloop | \
        while read -r _ ; do
            printTrack
        done
        printf "%s\n" "$STATUS_ERROR Error connecting to $HOST"
        sleep 5
    done
}

# do not block so we can receive signals
loop &
wait
