#!/bin/sh

. ./config

printVol() {

    ISMUTE=$(pamixer --get-mute)
    VOL=$(pamixer --get-volume)

    OPENPAVU="%{A3:pavucontrol &:}"
    VOLUP="%{A4:pamixer --increase 5 &:}"
    VOLDOWN="%{A5:pamixer --decrease 5 &:}"
    MUTE="%{A1:pamixer --toggle-mute &:}"

    FULL="$MUTE""$OPENPAVU""$VOLDOWN""$VOLUP"


    if [ "$ISMUTE" = "true" ]; then
        FULL="$FULL""%{F$COLOR_VOLUME_MUTED}""$ICON_VOL_MUTE $VOL%"
    else
        if [ "$VOL" -lt "$VOLUME_THRESHOLD" ] ; then
            FULL="$FULL""%{F$COLOR_VOLUME}""$ICON_VOL_LOW $VOL%"
        else
            FULL="$FULL""%{F$COLOR_VOLUME}""$ICON_VOL_HIGH $VOL%"
        fi
    fi

    FULL=$FULL"%{A}%{A}%{A}%{A}"

    printf "%s\n" "$FULL"

}

printVol

while true; do
    pactl subscribe | grep --line-buffered sink | \
    while read -r _ ; do
        printVol
    done
    printf "%s\n" "Error"
    sleep 1
done
