#!/bin/sh
while true; do
    OPENPAVU="%{A3:pavucontrol &:}"
    VOLUP="%{A4:pamixer --increase 5 &:}"
    VOLDOWN="%{A5:pamixer --decrease 5 &:}"
    MUTE="%{A1:pamixer --toggle-mute &:}"
    ISMUTE=$(pamixer --get-mute)
    VOL=$(pamixer --get-volume)
    if [ $ISMUTE = true ]; then
        FULL="$MUTE""$OPENPAVU""%{F#ffff6961}"" $VOL%""%{F#ffffffff}""%{A}""%{A}"
    else
        FULL="$MUTE""$OPENPAVU""$VOLDOWN""$VOLUP"" $VOL%""%{A}%{A}%{A}%{A}"
    fi

    echo "$FULL"

    sleep 0.5;
done
