#!/bin/bash

INTERFACE=$1
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit


while true; do
    SSID=$(iwgetid -r)
    QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    CLICK="%{A1:urxvt -e nmtui &:}"

    printf '%sSSID: %s (%s)\%{A}\n' "$CLICK" $SSID $QUALITY

    sleep 10
done
