#!/bin/bash

. ./config

OPENNMTUI="%{A1:urxvt -e nmtui &:}"

INTERFACE=$1

printWifi() {

    DEVICES=$(nmcli -t -f device,state,connection dev)

    if [[ "$DEVICES" != *"$INTERFACE"* ]] ; then
        printf '%s %s\n' "$WIFI_ICON_DISCONNECTED" "Unavailable"
        exit
    fi

    DEVICE=$(echo "$DEVICES" | grep "$INTERFACE")
    LIST_WIFI=$(nmcli -t -f ssid,signal dev wifi)

    IFS=':' read -r -a array <<< "$DEVICE"

    if [[ "${array[1]}" = "unavailable" ]] ; then
        printf '%s%s%s Disabled%s%s\n' "$OPENNMTUI" "$WIFI_ICON_DISCONNECTED" "$WIFI_DISABLED" "$PANEL_COLOR_END" "%{A}"
    elif [[ "${array[1]}" = "disconnected" ]] ; then
        printf '%s%s%s Disconnected%s%s\n' "$OPENNMTUI" "$WIFI_ICON_DISCONNECTED" "$WIFI_DISCONNECTED" "$PANEL_COLOR_END" "%{A}"
    elif [[ "${array[1]}" = "connecting"* ]] ; then
        printf '%s%s%s Connecting%s%s\n' "$OPENNMTUI" "$WIFI_ICON_DISCONNECTED" "$WIFI_DISCONNECTED" "$PANEL_COLOR_END" "%{A}"
    elif [[ "${array[1]}" = "connected" ]] ; then
        SSID="${array[2]}"
        QUALITY=$(echo $LIST_WIFI | grep "$SSID" | awk -F":" '{print $2}' | awk '{print $1}' | tr -d '\n')
        printf '%s%s%s %s (%s%%)%s%s\n' "$OPENNMTUI" "$WIFI_ICON_CONNECTED" "$WIFI_CONNECTED" "$SSID" "$QUALITY" "$PANEL_COLOR_END" "%{A}"
    fi

}

printWifi

while true; do
    nmcli m | grep --line-buffered "$INTERFACE" | \
    while read -r _ ; do
        printWifi
    done
    printf "wifi: %s\n" "Error watching nmcli m"
    sleep 1
done
