#!/bin/sh

num_mon=$(bspc query -M | wc -l)

. ./config


bspc subscribe report | \
while read -r line ; do
    case $line in
        W*)
            # bspwm's state
            wm="%{A5:bspc desktop -f next:}%{A4:bspc desktop -f prev:}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                ICON=$WORKSPACE_ICON_FREE
                case $item in
                    [mM]*)
                        [ $num_mon -lt 2 ] && shift && continue
                        case $item in
                            m*)
                                # monitor
                                ;;
                            M*)
                                # focused monitor
                                ;;
                        esac
                        wm="${wm}%{A:bspc monitor -f ${name}:} ${name} %{A}"
                        ;;
                        # [fFoOuU]*)
                    [fFoOuU]*)
                        case $item in
                            f*)
                                # free desktop
                                ;;
                            F*)
                                # focused free desktop
                                ICON=$WORKSPACE_ICON_FOCUSED
                                ;;
                            o*)
                                # occupied desktop
                                ICON=$WORKSPACE_ICON_OCCUPIED
                                ;;
                            O*)
                                # focused occupied desktop
                                ICON=$WORKSPACE_ICON_FOCUSED
                                ;;
                            u*)
                                # urgent desktop
                                ICON=$WORKSPACE_ICON_URGENT
                                ;;
                            U*)
                                # focused urgent desktop
                                ICON=$WORKSPACE_ICON_URGENT_FOCUSED
                                ;;
                        esac
                        wm="${wm}%{A:bspc desktop -f ${name}:} $ICON %{A} "
                        ;;
                    # [LTG]*)
                    #     # layout, state and flags
                    #     wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
                    #     ;;
                esac
                shift
            done
            wm="${wm}""%{A}%{A}"
            ;;
    esac
    printf "%s\n" "${wm}"
done
