#!/bin/bash

# trap "kill 0" SIGINT SIGUSR1

### redshift

COLOR_RED="#E25852"
REDSHIFT_ICON_ENABLED=" "
REDSHIFT_ICON_DISABLED="%{F$COLOR_RED} %{F-}"

ENABLED=1
TEMP="6500K"


if [ ${XDG_RUNTIME_DIR:+x} ] ; then
    TMP=$XDG_RUNTIME_DIR
else
    TMP=/tmp
fi

RED_TEMP=$TMP/redshift

# get info into pipe
pkill -x -USR1 "redshift"
sleep 0.5 # give redshift a moment to react
pkill -x -USR1 "redshift"

printRedshift() {

    ICON="$REDSHIFT_ICON_ENABLED"

    if [ $ENABLED -eq 0 ]; then
        ICON="$REDSHIFT_ICON_DISABLED"
    fi
    printf "%s%s%s%s\n" "$ICON" "$TEMP"
}

printRedshift

if [ $# -eq 0 ] ; then
    while true; do
        cat <>$RED_TEMP | \
        while read -r LINE ; do
            if [ "$LINE" = "Status: Enabled" ] ; then
                ENABLED=1
            elif [ "$LINE" = "Status: Disabled" ] ; then
                ENABLED=0
            elif [[ "$LINE" = "Color temperature: "*  ]] ; then
                TEMP=$(echo "$LINE" | sed 's/.*: //')
            fi
            printRedshift
        done
        sleep 1
    done
fi
