#!/bin/bash

# trap "kill 0" SIGINT SIGUSR1

### redshift

COLOR_RED="#E25852"
FOREGROUND_RED='#e1e5ea'
BACKGROUND_RED='#cc575d'

REDSHIFT_ICON=""

ENABLED=1
TEMP="6500K"


if [ ${XDG_RUNTIME_DIR:+x} ] ; then
    TMP=$XDG_RUNTIME_DIR
else
    TMP=/tmp
fi

RED_TEMP=$TMP/redshift

# get info into pipe
pkill -x -USR1 "redshift"
sleep 0.5 # give redshift a moment to react
pkill -x -USR1 "redshift"

printRedshift() {

    FULL="  $REDSHIFT_ICON  $TEMP  "

    if [ $ENABLED -eq 0 ]; then
      FULL="%{F$FOREGROUND_RED}""%{B$BACKGROUND_RED}""%{u$FOREGROUND_RED}""$FULL""%{F-}""%{B-}""%{u-}"
    fi
    printf "%s\n" "$FULL"
}

printRedshift

if [ $# -eq 0 ] ; then
    while true; do
        cat <>$RED_TEMP | \
        while read -r LINE ; do
            if [ "$LINE" = "Status: Enabled" ] ; then
                ENABLED=1
            elif [ "$LINE" = "Status: Disabled" ] ; then
                ENABLED=0
            elif [[ "$LINE" = "Color temperature: "*  ]] ; then
                TEMP=$(echo "$LINE" | sed 's/.*: //')
            fi
            printRedshift
        done
        sleep 1
    done
fi
