#!/bin/sh

### volume
VOLUME_THRESHOLD=40

ICON_VOL_LOW=""
ICON_VOL_HIGH=""
ICON_VOL_MUTE=""
COLOR_VOLUME_MUTED="#E25852"

printVol() {

    ISMUTE=$(pamixer --get-mute)
    VOL=$(pamixer --get-volume)

    FULL=""


    if [ "$ISMUTE" = "true" ]; then
        FULL="$FULL""%{F$COLOR_VOLUME_MUTED}""$ICON_VOL_MUTE%{F-} $VOL%"
    else
        if [ "$VOL" -lt "$VOLUME_THRESHOLD" ] ; then
            FULL="$FULL""$ICON_VOL_LOW $VOL%"
        else
            FULL="$FULL""$ICON_VOL_HIGH $VOL%"
        fi
    fi

    # FULL=$FULL

    printf "%s\n" "$FULL"

}

printVol

while true; do
    pactl subscribe | grep --line-buffered sink | \
    while read -r _ ; do
        printVol
    done
    printf "%s\n" "Error"
    sleep 1
done