#!/bin/sh

VPN_ICON_CONNECTED=""
VPN_ICON_DISCONNECTED="%{F#E25852}%{F-}"


printVPN() {

    FULL=""

    ps -aux | grep openvpn | grep -v 'grep' | grep -v 'sed' > /dev/null
    if [ $? -eq 1 ]; then
        VPN="No Connection"
        FULL="$FULL""$VPN_ICON_DISCONNECTED""   $VPN"
    else
        VPN=$(nmcli c show --active | grep vpn | awk '{ printf "%s\n", $1 }')
        FULL="$FULL""$VPN_ICON_CONNECTED""   $VPN"
    fi

    FULL="$FULL"

    printf "%s\n" "$FULL"

}

printVPN


while true; do
    nmcli m | grep --line-buffered "connection profile changed" | \
    while read -r _ ; do
        printVPN
    done
    printf "vpn: %s\n" "Error watching nmcli m"
    sleep 1
done
