#!/bin/sh

VPN_FG_DISCONNECTED="#E1E5EA"
VPN_BG_DISCONNECTED="#CC575D"
PANEL_BG="#2A303B"

VPN_ICON_CONNECTED="  "
VPN_ICON_DISCONNECTED="%{F$VPN_FG_DISCONNECTED}""%{B$VPN_BG_DISCONNECTED}""%{o$PANEL_BG}""%{u$PANEL_BG}""    ""%{F-}""%{B-}"


printVPN() {

    FULL=""

    ps -aux | grep openvpn | grep -v 'grep' | grep -v 'sed' > /dev/null
    if [ $? -eq 1 ]; then
        VPN="No Connection"
        FULL="$FULL""$VPN_ICON_DISCONNECTED""  $VPN"
    else
        VPN=$(nmcli c show --active | grep vpn | awk '{ printf "%s\n", $1 }')
        FULL="$FULL""$VPN_ICON_CONNECTED""  $VPN"
    fi

    printf "%s\n" "$FULL""%{u-}""%{o-}"

}

printVPN


while true; do
    nmcli m | grep --line-buffered "connection profile changed" | \
    while read -r _ ; do
        printVPN
    done
    printf "vpn: %s\n" "Error watching nmcli m"
    sleep 1
done
