#!/bin/sh

num_mon=$(bspc query -M | wc -l)

##########################
### colors
##########################

COLOR_RED="#E25852"
COLOR_WHITE="#FFFFFF"
COLOR_WHITE2='#B3BDCB'
COLOR_GREEN="#89b09c"
COLOR_PURPLE="#a8a2c0"
COLOR_GREY="#788491"
COLOR_GREY2="#2A303B"
COLOR_BLUE='#5294E2'

COLOR_DEFAULT_FG=$COLOR_WHITE2
COLOR_DEFAULT_BG=$COLOR_GREY2

COLOR_MONITOR_FG="#788491"
COLOR_MONITOR_BG=$COLOR_DEFAULT_BG

COLOR_FOCUSED_MONITOR_FG="#788491"
COLOR_FOCUSED_MONITOR_BG=$COLOR_DEFAULT_BG

COLOR_FREE_FG="#788491"
COLOR_FREE_BG=$COLOR_DEFAULT_BG

COLOR_OCCUPIED_FG=$COLOR_DEFAULT_FG
COLOR_OCCUPIED_BG=$COLOR_DEFAULT_BG

COLOR_FOCUSED_FG=$COLOR_DEFAULT_FG
COLOR_FOCUSED_BG=$COLOR_BLUE

COLOR_URGENT_FG="#E25852"
COLOR_URGENT_BG=$COLOR_DEFAULT_BG

PANEL_COLOR_END="%{F-}%{B-}%{u-}%{o-}"
ICON_FREE="      "
ICON_OCCUPIED="      "
ICON_FOCUSED="      "

LINES="%{u$COLOR_DEFAULT_BG}""%{o$COLOR_DEFAULT_BG}"

#workspaces
WORKSPACE_ICON_FREE="%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}""$LINES""$ICON_FREE""$PANEL_COLOR_END"
WORKSPACE_ICON_OCCUPIED="%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}""$LINES""$ICON_OCCUPIED""$PANEL_COLOR_END"
WORKSPACE_ICON_FOCUSED="%{F$COLOR_FOCUSED_FG}%{B$COLOR_FOCUSED_BG}""$LINES""$ICON_FOCUSED""$PANEL_COLOR_END"
WORKSPACE_ICON_URGENT="%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}""$LINES""$ICON_FREE""$PANEL_COLOR_END"
WORKSPACE_ICON_URGENT_FOCUSED="%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}""$LINES""%{u$COLOR_DEFAULT_BG}""$ICON_FOCUSED""$PANEL_COLOR_END"

bspc subscribe report | \
while read -r line ; do
    case $line in
        W*)
            # bspwm's state
            wm="%{A5:bspc desktop -f next:}%{A4:bspc desktop -f prev:}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                ICON=$WORKSPACE_ICON_FREE
                case $item in
                    [mM]*)
                        [ $num_mon -lt 2 ] && shift && continue
                        case $item in
                            m*)
                                # monitor
                                ;;
                            M*)
                                # focused monitor
                                ;;
                        esac
                        wm="${wm}%{A1:bspc monitor -f ${name}:} ${name} %{A}"
                        ;;
                        # [fFoOuU]*)
                    [fFoOuU]*)
                        case $item in
                            f*)
                                # free desktop
                                ;;
                            F*)
                                # focused free desktop
                                ICON=$WORKSPACE_ICON_FOCUSED
                                ;;
                            o*)
                                # occupied desktop
                                ICON=$WORKSPACE_ICON_OCCUPIED
                                ;;
                            O*)
                                # focused occupied desktop
                                ICON=$WORKSPACE_ICON_FOCUSED
                                ;;
                            u*)
                                # urgent desktop
                                ICON=$WORKSPACE_ICON_URGENT
                                ;;
                            U*)
                                # focused urgent desktop
                                ICON=$WORKSPACE_ICON_URGENT_FOCUSED
                                ;;
                        esac
                        wm="${wm}%{A1:bspc desktop -f ${name}:}""$ICON""%{A}"
                        ;;
                    # [LTG]*)
                    #     # layout, state and flags
                    #     wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
                    #     ;;
                esac
                shift
            done
            wm="${wm}""%{A}%{A}"
            ;;
    esac
    printf "%s\n" "${wm}"
done
