#! /bin/bash
#
# Example panel for lemonbar

. ./config

while read -r line ; do
    case $line in
        S*)
            # CLOCK output
            CLOCK="%{F$COLOR_CLOCK_FG}%{B$COLOR_CLOCK_BG}  ${line#?}  %{B-}%{F-}"
            ;;
        B*)
            # BATTERY output
            BATTERY="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-} ${SEPARATOR}"
            ;;
        X*)
            # BRIGHTNESS output
            BRIGHTNESS="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-} ${SEPARATOR}"
            ;;
        Y*)
            # WIFI output
            WIFI="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-} ${SEPARATOR}"
            ;;
        R*)
            # REDSHIFT output
            REDSHIFT="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-} ${SEPARATOR}"
            ;;
        V*)
            # VOLUME output
            VOLUME="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-} ${SEPARATOR}"
            ;;
        N*)
            # VPN output
            VPN="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-} ${SEPARATOR}"
            ;;
        M*)
            # MPRIS output
            MPRIS="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-} ${SEPARATOR}"
            ;;
        W*)
            # MPRIS output
            WORKSPACE="${SEPARATOR} %{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
    esac
    printf "%s\n" "%{l}${WORKSPACE}%{c}${CLOCK}%{r}${MPRIS} ${WIFI} ${BRIGHTNESS} ${BATTERY} ${REDSHIFT} ${VOLUME} ${VPN} "
done
