#! /bin/bash
#
# Example panel for lemonbar

. ./panel_colors

num_mon=$(bspc query -M | wc -l)

sp="    "
while read -r line ; do
    case $line in
        S*)
            # clock output
            clock="%{F$COLOR_CLOCK_FG}%{B$COLOR_CLOCK_BG}  ${line#?}  %{B-}%{F-}"
            ;;
        B*)
            # battery output
            battery="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        X*)
            # brightness output
            brightness="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        Y*)
            # wifi output
            wifi="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        R*)
            # redshift output
            redshift="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        V*)
            # redshift output
            volume="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        N*)
            # vpn output
            vpn="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        M*)
            mpris="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        G*)
            gmusic="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        W*)
            # bspwm's state
            wm="%{A5:bspc node -f @next.occupied\:/:}%{A4:bspc node -f @prev.occupied\:/:}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                ICON=
                case $item in
                    [mM]*)
                        [ $num_mon -lt 2 ] && shift && continue
                        case $item in
                            m*)
                                # monitor
                                FG=$COLOR_MONITOR_FG
                                BG=$COLOR_MONITOR_BG
                                ;;
                            M*)
                                # focused monitor
                                FG=$COLOR_FOCUSED_MONITOR_FG
                                BG=$COLOR_FOCUSED_MONITOR_BG
                                ;;
                        esac
                        wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
                        ;;
                        # [fFoOuU]*)
                    [FoOuU]*)
                        case $item in
                            f*)
                                # free desktop
                                FG=$COLOR_FREE_FG
                                BG=$COLOR_FREE_BG
                                ;;
                            F*)
                                # focused free desktop
                                FG=$COLOR_FOCUSED_FREE_FG
                                BG=$COLOR_FOCUSED_FREE_BG
                                ICON=
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_OCCUPIED_FG
                                BG=$COLOR_OCCUPIED_BG
                                ;;
                            O*)
                                # focused occupied desktop
                                FG=$COLOR_FOCUSED_OCCUPIED_FG
                                BG=$COLOR_FOCUSED_OCCUPIED_BG
                                ICON=
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$COLOR_FOCUSED_URGENT_FG
                                BG=$COLOR_FOCUSED_URGENT_BG
                                ICON=
                                ;;
                        esac
                        wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} $ICON %{A}%{B-}%{F-}"
                        ;;
                    # [LTG]*)
                    #     # layout, state and flags
                    #     wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
                    #     ;;
                esac
                shift
            done
            wm="${wm}""%{A}%{A}"
            ;;
    esac
    printf "%s\n" "%{l}${sp} ${wm} ${sp} ${gmusic} ${sp} ${mpris}%{c}${clock}%{r}${wifi} ${sp} ${brightness} ${sp} ${battery} ${sp} ${redshift} ${sp} ${volume} ${sp} ${vpn} ${sp}"
done
