#! /bin/bash

. ./panel_colors
. ./profile

if pgrep "lemonbar" > /dev/null ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

MONITOR_WIDTH=$(bspc query -T -m | jshon -e rectangle -e width -u)
WINDOW_GAP=$(bspc query -T -d | jshon -e windowGap)
PANEL_GAP=$((2 * WINDOW_GAP))
PANEL_WIDTH=$((MONITOR_WIDTH - PANEL_GAP))
TOP_GAP=25

# MONITOR_WIDTH=$(i3-msg -t "get_workspaces" | jshon -e 0 -e rect -e width)
# PANEL_WIDTH=$((MONITOR_WIDTH))

bspc config top_padding $(($PANEL_HEIGHT))

modules/redshift | xargs -L 1 -d '\n' printf "R%s\n" > "$PANEL_FIFO" &
modules/date | xargs -L 1 -d '\n' printf "S%s\n" > "$PANEL_FIFO" &
modules/volume | xargs -L 1 -d '\n' printf "V%s\n" > "$PANEL_FIFO" &
modules/vpn | xargs -L 1 -d '\n' printf "N%s\n" > "$PANEL_FIFO" &
modules/battery | xargs -L 1 -d '\n' printf "B%s\n" > "$PANEL_FIFO" &
modules/brightness | xargs -L 1 -d '\n' printf "X%s\n" > "$PANEL_FIFO" &
modules/wifi wlp2s0 | xargs -L 1 -d '\n' printf "Y%s\n" > "$PANEL_FIFO" &
modules/workspace | xargs -L 1 -d '\n' printf "W%s\n" > "$PANEL_FIFO" &
modules/mediaplayer mopidy | xargs -L 1 -d '\n' printf "M%s\n" > "$PANEL_FIFO" &
modules/mediaplayer google-play-music-desktop-player | xargs -L 1 -d '\n' printf "G%s\n" > "$PANEL_FIFO" &

./panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g "$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$WINDOW_GAP"+"$TOP_GAP" -f "$PANEL_FONT" -f "$PANEL_ICONS" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
    sleep 0.05
    wid=$(xdo id -a "$PANEL_WM_NAME")
    tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
