#! /bin/bash
#
# Example panel for lemonbar

. ./panel_colors

sp="    "
while read -r line ; do
    case $line in
        S*)
            # clock output
            clock="%{F$COLOR_CLOCK_FG}%{B$COLOR_CLOCK_BG}  ${line#?}  %{B-}%{F-}"
            ;;
        B*)
            # battery output
            battery="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        X*)
            # brightness output
            brightness="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        Y*)
            # wifi output
            wifi="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        R*)
            # redshift output
            redshift="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        V*)
            # redshift output
            volume="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        N*)
            # vpn output
            vpn="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        M*)
            mpris="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
        G*)
            gmusic="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
            ;;
    esac
    printf "%s\n" "%{l}${gmusic} ${sp} ${mpris}%{c}${clock}%{r}${wifi} ${sp} ${brightness} ${sp} ${battery} ${sp} ${redshift} ${sp} ${volume} ${sp} ${vpn}"
done
