#! /bin/bash

trap "kill 0" SIGINT

. ./config

[ -e "$PANEL_TOP_FIFO" ] && rm "$PANEL_TOP_FIFO"
mkfifo "$PANEL_TOP_FIFO"

[ -e "$PANEL_BOT_FIFO" ] && rm "$PANEL_BOT_FIFO"
mkfifo "$PANEL_BOT_FIFO"

MONITOR_HEIGHT=$(bspc query -T -m | jshon -e rectangle -e height -u)
MONITOR_WIDTH=$(bspc query -T -m | jshon -e rectangle -e width -u)
WINDOW_GAP=$(bspc query -T -d | jshon -e windowGap)
PANEL_GAP=$((2 * WINDOW_GAP))
PANEL_WIDTH=$((MONITOR_WIDTH - PANEL_GAP))
TOP_GAP=$(((WINDOW_GAP/2)-(PANEL_HEIGHT/2)))
BOT_GAP=10


if [ $REDSHIFT_ENABLED -eq 1 ]; then
modules/redshift_panel | xargs -L 1 -d '\n' printf "R%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $DATE_ENABLED -eq 1 ]; then
modules/date | xargs -L 1 -d '\n' printf "S%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $VOLUME_ENABLED -eq 1 ]; then
modules/volume | xargs -L 1 -d '\n' printf "V%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $VPN_ENABLED -eq 1 ]; then
modules/vpn | xargs -L 1 -d '\n' printf "N%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $BATTERY_ENABLED -eq 1 ]; then
modules/battery | xargs -L 1 -d '\n' printf "B%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $BRIGHTNESS_ENABLED -eq 1 ]; then
modules/brightness | xargs -L 1 -d '\n' printf "X%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $WIFI_ENABLED -eq 1 ]; then
modules/wifi wlp2s0 | xargs -L 1 -d '\n' printf "Y%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $MEDIAPLAYER_ENABLED -eq 1 ]; then
modules/mediaplayer google-play-music-desktop-player mopidy | xargs -L 1 -d '\n' printf "M%s\n" > "$PANEL_TOP_FIFO" &
fi
if [ $WORKSPACE_ENABLED -eq 1 ]; then
modules/workspace | xargs -L 1 -d '\n' printf "W%s\n" > "$PANEL_TOP_FIFO" &
fi

./panel_top < "$PANEL_TOP_FIFO" | lemonbar -a 32 -n "$PANEL_TOP_WM_NAME" -g "$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$WINDOW_GAP"+"$TOP_GAP" -f "$PANEL_FONT" -f "$PANEL_ICONS" -o -3 -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

# ./panel_bottom < "$PANEL_BOT_FIFO" | lemonbar -a 32 -n "$PANEL_BOT_WM_NAME" -g "$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$WINDOW_GAP"+$(($MONITOR_HEIGHT  - $PANEL_HEIGHT - $BOT_GAP)) -f "$PANEL_FONT" -f "$PANEL_ICONS" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_TOP_WM_NAME")
tries_left=20
while [ -z "$wid" ] && [ "$tries_left" -gt 0 ] ; do
    sleep 0.05
    wid=$(xdo id -a "$PANEL_TOP_WM_NAME")
    tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wid=$(xdo id -a "$PANEL_BOT_WM_NAME")
tries_left=20
while [ -z "$wid" ] && [ "$tries_left" -gt 0 ] ; do
    sleep 0.05
    wid=$(xdo id -a "$PANEL_BOT_WM_NAME")
    tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"


wait
