#!/bin/bash

start ()
{
    if pgrep "lemonbar" > /dev/null
    then
        printf "%s\n" "The panel is already running."
    else
        bash -c "cd ~/.config/panel/ && (nohup ./panel > /dev/null 2>&1) &"
    fi
}

stop ()
{
    pkill -f "lemonbar"
    pkill -f "/bin/bash ./panel_bar"
    pkill -f "/bin/bash ./panel"
    pkill -f "i3subscribe workspace"
    pkill -f "modules/mediaplayer"
    pkill -f "modules/vpn"
    pkill -f "modules/redshift"
    pkill -f "modules/date"
    pkill -f "modules/volume"
    pkill -f "modules/battery"
    pkill -f "modules/brightness"
    pkill -f "modules/wifi"
}

toggle ()
{
    if pgrep "lemonbar" > /dev/null
    then
        printf "%s\n" "The panel is already running."
        stop
    else
        echo "Stopped"
        start
    fi
}

if [ -n "$1" ] ; then
    if [ "$1" = "start" ] ; then
        start
    elif [ "$1" = "stop" ] ; then
        stop
    fi
else
    toggle
fi
